const obras = [
    {   id: 1,
        nb: "CALAVERA", 
        precio: 6500, 
        med: "60x60", 
        img1: "https://via.placeholder.com/300", 
    },
    {   id: 2,
        nb: "PAPA BUDA", 
        precio: 4000, 
        med: "40x40",
        img1: "https://via.placeholder.com/300", 
    },
    {   id: 3,
        nb: "PSICODELICO",
        precio: 4500,
        med: "40x70",
        img1: "https://via.placeholder.com/300",
    },
    {   id: 4,
        nb: "TRES MUJERES", 
        precio: 6500, 
        med: "40x70", 
        img1: "https://via.placeholder.com/300", 
    },
    {   id: 5,
        nb: "CARAS", 
        precio: 4500, 
        med: "50x50", 
        img1: "https://via.placeholder.com/300"
    },
    {   id: 6,
        nb: "EL CHICO", 
        precio: 6500, 
        med: "50x70",
        img1: "https://via.placeholder.com/300"
    },
    {   id: 7,
        nb: "JIRAFA", 
        precio: 7000, 
        med: "40x80", 
        img1: "https://via.placeholder.com/300"
    },
    {   id: 8,
        nb: "EL DIABLO Y LA NIÑA", 
        precio: 5000, 
        med: "50x70", 
        img1: "https://via.placeholder.com/300"
    },
    {   id: 9,
        nb: "ALIEN VOLANDO", 
        precio: 4000, 
        med: "30x40", 
        img1: "https://via.placeholder.com/300"
    },
    {   id: 10,
        nb: "GALAXIA", 
        precio: 6500, 
        med: "50x70", 
        img1: "https://via.placeholder.com/300"
    },
    {   id: 11,
        nb: "SOMBRAS CAMINANDO", 
        precio: 4000, 
        med: "30x40", 
        img1: "https://via.placeholder.com/300"
    },
    {   id: 12,
        nb: "SELVA TROPICAL", 
        precio: 6000, 
        med: "40x70", 
        img1: "https://via.placeholder.com/300"
    },
    {   id: 13,
        nb: "LOS NIÑOS", 
        precio: 4000, 
        med: "40x40", 
        img1: "https://via.placeholder.com/300"
    },
    {   id: 14,
        nb: "EL DRAGÓN", 
        precio: 7000, 
        med: "40x70", 
        img1: "https://via.placeholder.com/300"
    },
    {   id: 15,
        nb: "GRITO DE COLOR", 
        precio: 15000, 
        med: "100x120", 
        img1: "https://via.placeholder.com/300" 
    }   
]

export default obras;